### ISSUE TITLE
dependency aws s3 problems

### ISSUE THREAD

**Issue by jarnaiz** [Upplication/Amazon-S3-FileSystem-NIO2#37]
I cant create  a instance using this code:

```java
 Map<String, Object> env = new HashMap<>();
        env.put(AmazonS3Factory.ACCESS_KEY, accessKey);
        env.put(AmazonS3Factory.SECRET_KEY, secretKey);

try {
            return FileSystems.newFileSystem(uri, env, cl);
        } catch (FileSystemAlreadyExistsException e) {
            return FileSystems.getFileSystem(uri);
        } catch (IOException e) {
            return null;
        }
```

and the dependency pomx.ml

```xml

        <dependency>
            <groupId>com.upplication</groupId>
            <artifactId>s3fs</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
```

I got:

```java
Caused by: java.lang.NoSuchMethodError: com.amazonaws.services.s3.AmazonS3Client.<init>(Lcom/amazonaws/auth/AWSCredentialsProvider;Lcom/amazonaws/ClientConfiguration;Lcom/amazonaws/metrics/RequestMetricCollector;)V
	at com.upplication.s3fs.AmazonS3ClientFactory.createAmazonS3(AmazonS3ClientFactory.java:11) [s3fs-1.0.0-SNAPSHOT.jar:]
	at com.upplication.s3fs.AmazonS3ClientFactory.createAmazonS3(AmazonS3ClientFactory.java:8) [s3fs-1.0.0-SNAPSHOT.jar:]
	at com.upplication.s3fs.AmazonS3Factory.getAmazonS3(AmazonS3Factory.java:53) [s3fs-1.0.0-SNAPSHOT.jar:]
	at com.upplication.s3fs.S3FileSystemProvider.getAmazonS3(S3FileSystemProvider.java:472) [s3fs-1.0.0-SNAPSHOT.jar:]
	at com.upplication.s3fs.S3FileSystemProvider.createFileSystem(S3FileSystemProvider.java:468) [s3fs-1.0.0-SNAPSHOT.jar:]
	at com.upplication.s3fs.S3FileSystemProvider.newFileSystem(S3FileSystemProvider.java:102) [s3fs-1.0.0-SNAPSHOT.jar:]
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:332) [rt.jar:1.7.0_09]
```

maybe we need to add this dependency to the s3fs project:
```xml
<dependency>
	<groupId>com.amazonaws</groupId>
	<artifactId>aws-java-sdk-core</artifactId>
	<version>1.9.4</version>
</dependency>

```

**Comment by jarnaiz** [comment]
I dont know why travis works well :/ maybe some internal load of this dependencies when run with the test scope.

**Comment by jarnaiz** [comment]
maybe are internal conclicts of my project: https://github.com/aws/aws-sdk-java/issues/384

**Comment by jarnaiz** [comment]
ok, it was a problem with my project, we import a old version of aws-sdk. fixed.
