### ISSUE TITLE
I cant load S3FileSystemProvider inside ear

### ISSUE THREAD

**Issue by jarnaiz** [Upplication/Amazon-S3-FileSystem-NIO2#39]
FileSystems.getFileSystem(uri) use ClassLoader.getSystemClassLoader() and i cant load com.upplication.s3fs.S3FileSystemProvider inside ear because Jboss 7 use module class loader.

* http://osdir.com/ml/java.jboss.user/2003-10/msg00396.html
* http://www.coderanch.com/t/89900/JBoss/reading-properties-file
* http://www.javacodegeeks.com/2012/09/jboss-as-7-classloading-explained.html

What is the correct way? It is a jboss problem or I am doing something wrong?

**Comment by jarnaiz** [comment]
Workaround:

```java
 try {
                return FileSystems.getFileSystem(newUri);
            }
            catch (ProviderNotFoundException pe){
                // if not found in ClassLoader.getSystemClassLoader() we use custom class loader
                ServiceLoader<FileSystemProvider> sl = ServiceLoader
                        .load(FileSystemProvider.class, cl);
                for (FileSystemProvider provider: sl) {
                    if (uri.getScheme().equalsIgnoreCase(provider.getScheme())) {
                        return provider.getFileSystem(uri);
                    }
                }
                throw new ProviderNotFoundException("Provider \"" + uri.getScheme() + "\" not found");
            }
```

**Comment by jarnaiz** [comment]
Workaround:

```java
 try {
                return FileSystems.getFileSystem(newUri);
            }
            catch (ProviderNotFoundException pe){
                // if not found in ClassLoader.getSystemClassLoader() we use custom class loader
                ServiceLoader<FileSystemProvider> sl = ServiceLoader
                        .load(FileSystemProvider.class, Thread.currentThread().getContextClassLoader());
                for (FileSystemProvider provider: sl) {
                    if (uri.getScheme().equalsIgnoreCase(provider.getScheme())) {
                        return provider.getFileSystem(uri);
                    }
                }
                throw new ProviderNotFoundException("Provider \"" + uri.getScheme() + "\" not found");
            }
```

**Comment by jarnaiz** [comment]
I try to set the META-INF/services/java.nio.file.spi.FileSystemProvider inside the ear, inside the war and inside all the ejbs modules but without luck :(

**Comment by pditommaso** [comment]
It looks weird. Does it mean that JBoss is unable to load any service by using `java.util.ServiceLoader` ?

**Comment by jarnaiz** [comment]
I can't do that with the `FileSystems.getFileSystem(uri);` but ```FileSystems.newFileSystems(...)``` works well because i can set the classloader. Maybe Its because I dont undertand very well the JBoss class loader system

**Comment by jarnaiz** [comment]
I have some other strange bugs with wildfly 8.2 :(

If I use: ```FileSystems.newFileSystem(uri, env, Thread.currentThread().getContextClassLoader());```
```
java.util.ServiceConfigurationError: java.nio.file.spi.FileSystemProvider: Provider com.sun.nio.zipfs.ZipFileSystemProvider not found
	at java.util.ServiceLoader.fail(ServiceLoader.java:231)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:181)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:365)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:445)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:330)
```

And if I change it for: ```FileSystems.newFileSystem(uri, env, ClassLoader.getSystemClassLoader());``` then the SergiceLoader cant find the S3Provider. Its a wildfly bug or what?

**Comment by smartrchauhan** [comment]
Is there any solution for above problem? I am also facing the same issue, please help

**Comment by jarnaiz** [comment]
@smartrchauhan have you tried with another version? wildfly 9.0.2?

**Comment by jarnaiz** [comment]
I try to use with Wildfly 10 but without success. But here is my research:

```FileSystems.newFileSystem(uri, env, Thread.currentThread().getContextClassLoader());``` and  ```FileSystems.newFileSystem(uri, env, this.getClass().getClassLoader());``` use the module class loader and, as you can read: https://docs.jboss.org/author/display/WFLY10/Class+Loading+in+WildFly#ClassLoadinginWildFly-AccessingJDKclasses Not all JDK classes are exposed. 
I try to expose com/sun/nio/zipfs/ZipFileSystemProvider creating a file: jboss-deployment-structure.xml and saving it in the root of my ear file with the content:
```xml
<jboss-deployment-structure xmlns="urn:jboss:deployment-structure:1.1">
    <deployment>
        <dependencies>
            <system export="true">
                <paths>
                    <path name="com/sun/nio/zipfs/ZipFileSystemProvider"/>
                </paths>
            </system>
        </dependencies>
    </deployment>
</jboss-deployment-structure>
```
but thats not works :(

Instead if you try to use ```FileSystems.newFileSystem(uri, env);``` then s3fs is not found, I think that happens because I load s3fs as a Jar lib inside my ear and only my ear can access to it. When you dont set the ClassLoader I think the ```ClassLoader.getSystemClassLoader()``` is used. If I try ```FileSystems.newFileSystem(uri, env, ClassLoader.getSystemClassLoader());``` I get: ```java.nio.file.ProviderNotFoundException: Provider "s3" not found```

So, maybe if I save my s3fs as a system library or global module: https://docs.jboss.org/author/display/WFLY10/Class+Loading+in+WildFly#ClassLoadinginWildFly-GlobalModules Maybe it work. But I dont want to expose as a global module and I have not tried

What Im doing is use the S3FileSystemProvider directly:

```java
new S3FileSystemProvider().newFileSystem(uri, env);
```` 
And maybe create a singleton or something

Any help or suggestions will be very welcome!

Cheers!

**Comment by sbeimin** [comment]
Over the past couple of days I've been researching this exact same problem, only with tomcat instead of  JBOSS.
The problem boils down to:
`java.nio.file.spi.FileSystemProvider.loadInstalledProviders()`

which uses `ServiceLoader<FileSystemProvider> sl = ServiceLoader.load(FileSystemProvider.class, ClassLoader.getSystemClassLoader());` to discover all the FileSystemProviders.

Tomcat and JBOSS hijack the System Classloader for security reasons and to prevent ClassLoader-pinning leaks when undeploying web applications.

Christopher Schultz, from tomcat, suggested:
1. Place your s3fs.jar in Tomcat's bin/ directory
2. Explicitly set the CLASSPATH in bin/setenv.sh to point to bin/s3fs.jar
which probably exposes the S3FileSystemProvider to tomcat's SystemClassLoader.

If you don't want to make changes to your Tomcat/JBOSS I've made a fugly hack that might work. I haven't tested it very much though.

	/*
	 * This is a very dirty hack to get around the fact that FileSystemProvider uses 
	 * ClassLoader.getSystemClassLoader() to discover FileSystemProvider in the classpath.
	 * Tomcat hijacks the SystemClassLoader causing SPI not to function in tomcat.
	 */
	@SuppressWarnings("unused")
	private void customLoadInstalledProviders() {
		try {
			Field loadingProvidersField = FileSystemProvider.class.getDeclaredField("loadingProviders");
			Field installedProvidersField = FileSystemProvider.class.getDeclaredField("installedProviders");
			loadingProvidersField.setAccessible(true);
			installedProvidersField.setAccessible(true);

			loadingProvidersField.set(null, true);
			List<FileSystemProvider> installedProviders = loadInstalledProviders();
			installedProvidersField.set(null, installedProviders);
			loadingProvidersField.set(null, false);

			loadingProvidersField.setAccessible(false);
			installedProvidersField.setAccessible(false);
		} catch (NoSuchFieldException | IllegalAccessException e) {
			throw new RuntimeException("The hack didn't work.", e);
		}
	}

	// loads all installed providers
	private static List<FileSystemProvider> loadInstalledProviders() {
		List<FileSystemProvider> list = new ArrayList<FileSystemProvider>();

		ServiceLoader<FileSystemProvider> sl = ServiceLoader.load(FileSystemProvider.class, Thread.currentThread().getContextClassLoader());

		// ServiceConfigurationError may be throw here
		for (FileSystemProvider provider : sl) {
			String scheme = provider.getScheme();

			// add to list if the provider is not "file" and isn't a duplicate
			if (!scheme.equalsIgnoreCase("file")) {
				boolean found = false;
				for (FileSystemProvider p : list) {
					if (p.getScheme().equalsIgnoreCase(scheme)) {
						found = true;
						break;
					}
				}
				if (!found) {
					list.add(provider);
				}
			}
		}
		return list;
	}

**Comment by jarnaiz** [comment]
Hi @sbeimin,

thanks for share :)

I think your problem with tomcat is the same than my problem with wildfly, both servers narrow the classpath to control the libraries loaded and dont allow "easily" to add libraries to the System classloader.

But also with WildFly if I use Thread.currentThread().getContextClassLoader() Im getting the error:

```java
java.util.ServiceConfigurationError: java.nio.file.spi.FileSystemProvider: Provider com.sun.nio.zipfs.ZipFileSystemProvider not found
    at java.util.ServiceLoader.fail(ServiceLoader.java:231)
    at java.util.ServiceLoader.access$300(ServiceLoader.java:181)
    at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:365)
    at java.util.ServiceLoader$1.next(ServiceLoader.java:445)
    at java.nio.file.FileSystems.newFileSystem(FileSystems.java:330)
```
I try to expose com.sun.nio.zipfs.ZipFileSystemProvider but I'm not getting it to work :/
https://docs.jboss.org/author/display/WFLY10/Class+Loading+in+WildFly#ClassLoadinginWildFly-AccessingJDKclasses

Cheers!

**Comment by ulmermark** [comment]
**sbeimin** Approach appeared to work for loading the S3 provider ..but now the "file" FileSystemProvider native to the JDK is not working.

Run SpringBoot application configured as s3:///... for a file and all works fine...switch configuration to file:///.... and the application does not start with 

**_Caused by: java.nio.file.ProviderNotFoundException: Provider "file" not found_**

**Comment by ulmermark** [comment]
For those running Spring Boot applications from the FAT jar, the following approach appears to work as well.

Currently building SpringBoot FAT jar with gradle...nothig fancy, just the spring boot gradle plugin.

Extract the FAT JAR to a directory and then run the application from that directory:

**_java -classpath ./BOOT-INF/lib/*:./BOOT-INF/classes:. org.springframework.boot.loader.JarLauncher_**

Defeats the purpose of the executable JAR, but has gotten me over the hump and have not added any additional code to fix SPI and classloader issues

**Comment by tegataiprime** [comment]
I was able to extend the code supplied by @sbeimin to overcome the problem reported by @ulmermark.  I added some code to ensure that the default filesystem provider is included in the list of providers loaded from the Thread Context Classloader.  My Spring Boot app now loads jsr203-hadoop HDFS FileSystemProvider without the need to build a shaded jar.

    /*
    * This is a very dirty hack to get around the fact that FileSystemProvider uses
    * ClassLoader.getSystemClassLoader() to discover FileSystemProvider in the classpath.
    * Tomcat hijacks the SystemClassLoader causing SPI not to function in tomcat.
    */
    @SuppressWarnings("unused")
    @PostConstruct
    public void customLoadInstalledProviders() {
        try {
            Field loadingProvidersField = FileSystemProvider.class.getDeclaredField("loadingProviders");
            Field installedProvidersField = FileSystemProvider.class.getDeclaredField("installedProviders");
            loadingProvidersField.setAccessible(true);
            installedProvidersField.setAccessible(true);

            loadingProvidersField.set(null, true);

            List<FileSystemProvider> installedProviders = AccessController
                    .doPrivileged(new PrivilegedAction<List<FileSystemProvider>>() {
                        @Override
                        public List<FileSystemProvider> run() {
                            return threadClassLoaderInstalledProviders();
                        }});

            installedProvidersField.set(null, installedProviders);  // overwrite the current list of installed file system providers

            loadingProvidersField.set(null, false);

            loadingProvidersField.setAccessible(false);
            installedProvidersField.setAccessible(false);
        } catch (NoSuchFieldException | IllegalAccessException e) {
            throw new RuntimeException("The hack didn't work.", e);
        }
    }

    /*
        Load FileSystem Providers from Thread context class loader and from system class loader
     */
    private static List<FileSystemProvider> threadClassLoaderInstalledProviders() {

        List<FileSystemProvider> list = new ArrayList<>();

        FileSystemProvider defaultProvider = FileSystems.getDefault().provider();

        ServiceLoader<FileSystemProvider> sl = ServiceLoader.load(FileSystemProvider.class, ClassLoader.getSystemClassLoader());
        for (FileSystemProvider provider : sl){
            addProviderToList(list,provider);
        }

        ServiceLoader<FileSystemProvider> tsl = ServiceLoader.load(FileSystemProvider.class, Thread.currentThread().getContextClassLoader());
        for (FileSystemProvider provider : tsl) {
            addProviderToList(list,provider);
        }

        list.add(0,defaultProvider);

        return Collections.unmodifiableList(list);
    }

    private static void addProviderToList(List<FileSystemProvider> list, FileSystemProvider provider){

        String scheme = provider.getScheme();

        // add to list if the provider is not "file" and isn't a duplicate
        if (!scheme.equalsIgnoreCase("file")) {
            boolean found = false;
            for (FileSystemProvider p : list) {
                if (p.getScheme().equalsIgnoreCase(scheme)) {
                    found = true;
                    break;
                }
            }
            if (!found) {
                list.add(provider);
            }
        }

    }

**Comment by sbeimin** [comment]
Hey Guys!
I've finally gotten it to work (in tomcat)!

[This stackoverflow answer ](https://stackoverflow.com/questions/3420715/where-to-put-serviceloader-config-file-in-a-web-app/3421191#3421191) put me on the right path.

The part about the java.nio.file.spi.FileSystemProvider file inside the jar's META-INF/services/ directory is taken care of by the S3FS jar. What makes it work in a tomcat web application is copying said java.nio.file.spi.FileSystemProvider file into the WEB-INF/classes/META-INF/services directory!
(in a standard maven setup you can place a META-INF/services directory in your src/main/resources folder of your war module). Either way, make sure that your war contains the META-INF/services inside the WEB-INF/classes; not next to it as you might expect.

@jarnaiz and @tegataiprime: can you try if this also fixes the problem in an .ear in JBoss? If it does we can perhaps remove my fugly hack and @tegataiprime 's adaptation :)

PS.: If, in the future, we add a java.nio.file.spi.FileTypeDetector to this library that file should probably also be copied to your war/ear.

**Comment by sujitharao** [comment]
Hello,

We are facing similar problem and getting the exception
java.nio.file.ProviderNotFoundException: MCP provider not found.

Followed suggestion provided by @sbeimin  and have placed META-INF/services/java.nio.file.spi.FileSystemProvider in WEB-INF/classes directory. The content of java.nio.file.spi.FileSystemProvider file is "com.unisys.mcp.fs.CpFileSystemProvider".

We were not able to succeed in TOMCAT nor JBOSS.
Could you let us know if we are missing any other configurations

Thanks,
Sujitha
