### ISSUE TITLE
intermitent error when try to copy files

### ISSUE THREAD

**Issue by jarnaiz** [Upplication/Amazon-S3-FileSystem-NIO2#40]
```java
com.amazonaws.AmazonClientException: Unable to execute HTTP request: hostname in certificate didn't match: <upp-resources.s3-eu-west-1.amazonaws.com> != <*.cloudfront.net> OR <cloudfront.net> OR <*.cloudfront.net>
 at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:467) [aws-java-sdk-core-1.9.4.jar:]
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:295) [aws-java-sdk-core-1.9.4.jar:]
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3658) [aws-java-sdk-s3-1.9.4.jar:]
        at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:997) [aws-java-sdk-s3-1.9.4.jar:]
        at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:975) [aws-java-sdk-s3-1.9.4.jar:]
        at com.upplication.s3fs.util.S3Utils.getS3ObjectSummary(S3Utils.java:28) [s3fs-1.0.0-SNAPSHOT.jar:]
        at com.upplication.s3fs.util.S3Utils.getS3FileAttributes(S3Utils.java:65) [s3fs-1.0.0-SNAPSHOT.jar:]
        at com.upplication.s3fs.S3FileSystemProvider.readAttributes(S3FileSystemProvider.java:444) [s3fs-1.0.0-SNAPSHOT.jar:]
        at java.nio.file.Files.readAttributes(Files.java:1684) [rt.jar:1.7.0_25]
        at java.nio.file.CopyMoveHelper.copyToForeignTarget(CopyMoveHelper.java:109) [rt.jar:1.7.0_25]
        at java.nio.file.Files.copy(Files.java:1228) [rt.jar:1.7.0_25]
```

**Comment by jarnaiz** [comment]
Some ideas:

* https://forums.aws.amazon.com/message.jspa?messageID=388556 but it says that is a error with an older verion of the sdk.
* http://stackoverflow.com/questions/12755038/ssl-problems-with-s3-aws-using-the-java-api-hostname-in-certificate-didnt-mat older versiont too
