### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by mkotb** [Upplication/Amazon-S3-FileSystem-NIO2#65]
Hi,

I recently used your library and found that when I'm invoking `deleteIfExists`, I end up getting `400 Bad Request` as a reply. Could you direct me to be sure that this isn't an issue with how I'm using the library or if it is on my side, how to resolve it. Here's the stacktrace:

```Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Bad Request (Service: Amazon S3; Status Code: 400; Error Code: 400 Bad Request; Request ID: <omitted>), S3 Extended Request ID: <omitted>
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1406)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:950)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:723)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:475)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:437)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:386)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3999)
        at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1164)
        at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1139)
        at com.upplication.s3fs.util.S3Utils.getS3ObjectSummary(S3Utils.java:35)
        at com.upplication.s3fs.S3FileSystemProvider.exists(S3FileSystemProvider.java:612)
        at com.upplication.s3fs.S3FileSystemProvider.checkAccess(S3FileSystemProvider.java:466)
        at java.nio.file.Files.notExists(Files.java:2434)
        at com.upplication.s3fs.S3FileSystemProvider.delete(S3FileSystemProvider.java:395)
        at java.nio.file.spi.FileSystemProvider.deleteIfExists(FileSystemProvider.java:739)
        at java.nio.file.Files.deleteIfExists(Files.java:1165)```

Thanks c:

**Comment by jarnaiz** [comment]
Hello mktob,

Thanks for your feedback but I cant reproduce your error, maybe if you can create a 'test case' or give me the full stacktrace I could fix it.

Cheers!
