### ISSUE TITLE
S3FileSystemProvider.newInputStream issue

### ISSUE THREAD

**Issue by glassfox** [Upplication/Amazon-S3-FileSystem-NIO2#87]
s3fs version: 1.5.3

Hi all,

When I trying to read a lot of files. 2000 simultaneous files and more. Thrown exception:

```
com.amazonaws.SdkClientException: Unable to execute HTTP request: Timeout waiting for connection from pool 
    	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1038) 
    	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742) 
    	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716) 
    	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699) 
    	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667) 
    	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649) 
    	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513) 
    	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4191) 
    	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4138) 
    	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1385) 
    	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1263) 
    	at com.upplication.s3fs.S3FileSystemProvider.newInputStream(S3FileSystemProvider.java:347)  


```

Proposal:
After short investigation in internet, I found that S3Object object required to be closed in the end of use.
http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/S3Object.html#close--

**Comment by jarnaiz** [comment]
Hello @glassfox 

I try to reproduce the issue but I cant...
If i close the s3Object of the ```S3FileSystemProvider#newInputStream(...)```
```java
S3Object object = s3Path.getFileSystem().getClient().getObject(s3Path.getFileStore().name(), key);
```
Then we cant read the inputstream because I close the Object who hold the InputStream.

Maybe the problem is the AmazonS3Client itself or the Amazon S3 limits:
http://docs.aws.amazon.com/AmazonS3/latest/dev/request-rate-perf-considerations.html

**Comment by glassfox** [comment]
Hi,
Sure, required to close S3Object only after InputStream has been closed.
I propose to create wrapper for InputStream (example attached)
and wrap with it every InputStream returned by the function like this:

S3Object object = s3Path.getFileSystem().getClient().getObject(s3Path.getFileStore().name(), key);
InputStream res = object.getObjectContent();
if (res == null)
	throw new IOException(String.format("The specified path is a directory: %s", path));
return new InputStreamWrapper(res, object);

**Comment by glassfox** [comment]
You right.
So this solution do not solved my issue.
